services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-}:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-}:6379"
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/rails
      - ./storage:/rails/storage
    ports:
      - "${WEB_PORT:-}:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://redis:6379/0"
      RAILS_LOG_TO_STDOUT: "${RAILS_LOG_TO_STDOUT:-true}"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bin/rails server -b 0.0.0.0 -p 3000
    restart: unless-stopped

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://redis:6379/0"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - ./storage:/rails/storage
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl.crt:/etc/nginx/ssl/ssl.crt
      - ./docker/nginx/ssl.key:/etc/nginx/ssl/ssl.key
    depends_on:
      - web
    restart: unless-stopped

volumes:
  n8n_data:

networks:
  default:
